# Generated by Django 4.0.3 on 2023-10-05 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name_in_arabic', models.CharField(blank=True, max_length=200, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('uom', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=300, null=True)),
                ('supplier_site', models.CharField(blank=True, max_length=300, null=True)),
                ('vat_registratoion_number', models.CharField(blank=True, max_length=300, null=True)),
                ('attention', models.CharField(blank=True, max_length=150, null=True)),
                ('attention_one', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=300, null=True)),
                ('reference_number_one', models.CharField(blank=True, max_length=300, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('branch', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_supply', models.DateField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=300, null=True)),
                ('salesman_name', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice_number', models.IntegerField(blank=True, default=1, null=True)),
                ('invoice_issue_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('requistion_number', models.IntegerField(blank=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ship_to', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_inventroy', models.CharField(blank=True, max_length=150, null=True)),
                ('bill_to', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('taxable_amount', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('total_vat', models.FloatField(blank=True, null=True)),
                ('total_taxable_amount_exclude_vat', models.FloatField(blank=True, null=True)),
                ('total_exclude_vat', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('total_amount_due', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.product')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.setting')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.product')),
            ],
            options={
                'unique_together': {('invoice', 'product')},
            },
        ),
    ]
