# Generated by Django 4.0.3 on 2022-03-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('name_ar', models.CharField(max_length=70, null=True)),
                ('pos', models.BooleanField(null=True)),
                ('digital_menu', models.BooleanField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=70, null=True)),
                ('updated_by', models.CharField(max_length=70, null=True)),
                ('parent', models.CharField(max_length=70, null=True)),
                ('images', models.ImageField(null=True, upload_to='images')),
                ('is_parent', models.BooleanField(null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('code', models.CharField(max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('name_ar', models.CharField(max_length=70, null=True)),
                ('pos', models.BooleanField(null=True)),
                ('digital_menu', models.BooleanField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=70, null=True)),
                ('updated_by', models.CharField(max_length=70, null=True)),
                ('images', models.ImageField(null=True, upload_to='images')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('include_tax', models.BooleanField(null=True)),
                ('code', models.CharField(max_length=70, null=True, unique=True)),
                ('Category_id', models.ForeignKey(default=25, on_delete=django.db.models.deletion.SET_DEFAULT, to='invoice.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_orders', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('order_type', models.CharField(max_length=70, null=True)),
                ('created_by', models.CharField(max_length=70, null=True)),
                ('updated_by', models.CharField(max_length=70, null=True)),
                ('images', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Canceled', 'Canceled'), ('Reciverd', 'Reciverd'), ('Prepared', 'Prepared'), ('Ready', 'Ready'), ('Opened', 'Opened'), ('Closed', 'Closed')], default='Started', max_length=70)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('table_no', models.CharField(max_length=100, null=True)),
                ('waiter_name', models.CharField(max_length=100, null=True)),
                ('total_discount', models.CharField(max_length=100, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('payment_name', models.CharField(max_length=100, null=True)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.orders')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.products')),
            ],
        ),
    ]
