# Generated by Django 4.0.3 on 2022-03-14 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_supply', models.DateField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=300, null=True)),
                ('salesman_name', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice_number', models.IntegerField(blank=True, default=invoice.models.Invoice.number, null=True, unique=True)),
                ('invoice_issue_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('buyer_organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('street_name', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('additional_number', models.CharField(blank=True, max_length=150, null=True)),
                ('vat_number', models.IntegerField(blank=True, null=True)),
                ('other_buyer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('taxable_amount', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('total_vat', models.FloatField(blank=True, null=True)),
                ('total_taxable_amount_exclude_vat', models.FloatField(blank=True, null=True)),
                ('total_exclude_vat', models.FloatField(blank=True, null=True)),
                ('total_amount_due', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.product')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.setting')),
            ],
        ),
    ]
