# Generated by Django 4.0.3 on 2022-03-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_categories_products_orders_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Category_id',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
