# Generated by Django 4.0.3 on 2022-03-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rename_quantity_invoice_td_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='td_quantity',
            new_name='quantity',
        ),
    ]
