# Generated by Django 4.0.3 on 2022-03-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_rename_td_quantity_invoice_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='quantity',
            new_name='quantity_id',
        ),
    ]
