# Generated by Django 4.0.3 on 2022-03-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_rename_quantity_id_invoice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
